package model

enum class Team(val id: String) {
    BALTIMORE_HAWKS("70"),
    CHICAGO_BUTCHERS("325"),
    COLORADO_YETI("56"),
    PHILADELPHIA_LIBERTY("111"),
    YELLOWKNIFE_WRAITHS("58"),
    ARIZONA_OUTLAWS("73"),
    AUSTIN_COPPERHEADS("328"),
    NEW_ORLEANS_SECOND_LINE("114"),
    ORANGE_COUNTY_OTTERS("54"),
    SAN_JOSE_SABERCATS("52")
}